#!/usr/bin/env python3
"""Generates the Threadrinth logo SVGs and the in-app logo component.

The mark is a thread winding through a circular labyrinth to its center.
Run `./generate-assets.sh` to also rebuild the app icons.
"""
import math
from pathlib import Path

OUT = Path(__file__).parent
C = 256.0
THREAD = ("#FFC25C", "#FF8A3D")  # amber gradient, top-left to bottom-right
# The in-app logo follows the accent color: the same two shades, derived from
# the accent hue (amber is hue 30: #FFC25C and #FF8A3D).
ACCENT_LIGHT = "var(--th-logo-light, hsl(38 100% 68%))"
ACCENT_DEEP = "var(--th-logo-deep, hsl(24 100% 62%))"
WALL = "#343E4C"


def point(r, deg):
    a = math.radians(deg)
    return (C + r * math.cos(a), C + r * math.sin(a))


def fmt(pt):
    return f"{pt[0]:.1f} {pt[1]:.1f}"


def arc_cmd(r, d0, d1):
    """SVG arc from angle d0 to d1 (degrees, clockwise when d1 > d0)."""
    large = 1 if abs(d1 - d0) > 180 else 0
    sweep = 1 if d1 > d0 else 0
    return f"A{r} {r} 0 {large} {sweep} {fmt(point(r, d1))}"


def wall(r, gaps, gap_width):
    gaps = sorted(g % 360 for g in gaps)
    out = []
    for i, g in enumerate(gaps):
        start = g + gap_width / 2
        end = gaps[(i + 1) % len(gaps)] - gap_width / 2
        if end <= start:
            end += 360
        out.append(f"M{fmt(point(r, start))} {arc_cmd(r, start, end)}")
    return out


# (radius, gap angles, gap width); the thread passes through the gaps at
# -135 (outer), 40 (middle) and -150 (inner).
WALLS = [(192, [-135, 100], 30), (132, [40, -100, 170], 34), (72, [-150], 44)]
# Thread: in through the outer gap, clockwise around the outer corridor, back
# counter-clockwise around the inner one, then straight to the center. Round
# line joins soften the corners.
THREAD_PATH = (
    f"M{fmt(point(162, -135))} {arc_cmd(162, -135, 40)}"
    f" L{fmt(point(102, 40))} {arc_cmd(102, 40, -150)}"
    f" L{fmt((C, C))}"
)
TAIL_PATH = f"M{fmt(point(162, -135))} L{fmt(point(420, -135))}"
WALL_PATHS = "".join(f'<path d="{d}"/>' for r, g, w in WALLS for d in wall(r, g, w))


def mark(wall_attrs, tail=True):
    tail_el = f'<path d="{TAIL_PATH}" stroke="url(#thread)" stroke-width="26"/>' if tail else ""
    return (
        f'<g fill="none" stroke-linecap="round" stroke-linejoin="round">'
        f'<g {wall_attrs} stroke-width="24">{WALL_PATHS}</g>{tail_el}'
        f'<path d="{THREAD_PATH}" stroke="url(#thread)" stroke-width="26"/></g>'
    )


THREAD_GRADIENT = (
    '<linearGradient id="thread" x1="0" y1="0" x2="1" y2="1">'
    f'<stop offset="0" stop-color="{THREAD[0]}"/><stop offset="1" stop-color="{THREAD[1]}"/>'
    "</linearGradient>"
)

icon = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">
<defs>
<linearGradient id="tile" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#1C222C"/><stop offset="1" stop-color="#0E1116"/></linearGradient>
{THREAD_GRADIENT}
<clipPath id="clip"><rect x="16" y="16" width="480" height="480" rx="112"/></clipPath>
</defs>
<rect x="16" y="16" width="480" height="480" rx="112" fill="url(#tile)"/>
<g clip-path="url(#clip)">{mark(f'stroke="{WALL}"')}</g>
</svg>
"""

# Mark without the tile, used where the platform draws its own background.
mark_svg = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="40 40 432 432" width="432" height="432">
<defs>{THREAD_GRADIENT}</defs>
{mark(f'stroke="{WALL}"', tail=False)}
</svg>
"""

wordmark = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1640 512" width="1640" height="512">
<defs>
<linearGradient id="tile" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#1C222C"/><stop offset="1" stop-color="#0E1116"/></linearGradient>
{THREAD_GRADIENT}
<clipPath id="clip"><rect x="16" y="16" width="480" height="480" rx="112"/></clipPath>
</defs>
<rect x="16" y="16" width="480" height="480" rx="112" fill="url(#tile)"/>
<g clip-path="url(#clip)">{mark(f'stroke="{WALL}"')}</g>
<text x="560" y="318" font-family="Inter, 'Segoe UI', Helvetica, Arial, sans-serif" font-size="176" font-weight="800" letter-spacing="-4" fill="#E6EDF3">Thread<tspan fill="{THREAD[1]}">rinth</tspan></text>
</svg>
"""

(OUT / "threadrinth-icon.svg").write_text(icon)
(OUT / "threadrinth-mark.svg").write_text(mark_svg)
(OUT / "threadrinth-wordmark.svg").write_text(wordmark)

# In-app logo. Walls follow the text color so the mark works on every theme,
# and the thread follows the accent color.
vue_walls = "\n".join(
    f'\t\t\t<path d="{d}" />' for r, g, w in WALLS for d in wall(r, g, w)
)
vue = f"""<!-- Generated by branding/generate.py, do not edit by hand. -->
<script setup lang="ts">
import {{ useId }} from 'vue'

const gradientId = `threadrinth-thread-${{useId()}}`
</script>

<template>
\t<svg xmlns="http://www.w3.org/2000/svg" viewBox="40 40 432 432" aria-hidden="true">
\t\t<defs>
\t\t\t<linearGradient :id="gradientId" x1="0" y1="0" x2="1" y2="1">
\t\t\t\t<stop offset="0" style="stop-color: {ACCENT_LIGHT}" />
\t\t\t\t<stop offset="1" style="stop-color: {ACCENT_DEEP}" />
\t\t\t</linearGradient>
\t\t</defs>
\t\t<g
\t\t\tfill="none"
\t\t\tstroke="currentColor"
\t\t\tstroke-opacity="0.35"
\t\t\tstroke-width="24"
\t\t\tstroke-linecap="round"
\t\t>
{vue_walls}
\t\t</g>
\t\t<path
\t\t\td="{THREAD_PATH}"
\t\t\tfill="none"
\t\t\t:stroke="`url(#${{gradientId}})`"
\t\t\tstroke-width="26"
\t\t\tstroke-linecap="round"
\t\t\tstroke-linejoin="round"
\t\t/>
\t</svg>
</template>
"""
vue_dir = OUT.parent / "apps/app-frontend/src/components/brand"
vue_dir.mkdir(parents=True, exist_ok=True)
(vue_dir / "ThreadrinthMark.vue").write_text(vue)
