<!-- Generated by branding/generate.py, do not edit by hand. -->
<script setup lang="ts">
import { useId } from 'vue'

const gradientId = `threadrinth-thread-${useId()}`
</script>

<template>
	<svg xmlns="http://www.w3.org/2000/svg" viewBox="40 40 432 432" aria-hidden="true">
		<defs>
			<linearGradient :id="gradientId" x1="0" y1="0" x2="1" y2="1">
				<stop offset="0" style="stop-color: hsl(calc(var(--th-accent-hue, 30) + 8) 100% 68%)" />
				<stop offset="1" style="stop-color: hsl(calc(var(--th-accent-hue, 30) - 6) 100% 62%)" />
			</linearGradient>
		</defs>
		<g
			fill="none"
			stroke="currentColor"
			stroke-opacity="0.35"
			stroke-width="24"
			stroke-linecap="round"
		>
			<path d="M174.9 430.0 A192 192 0 0 1 89.7 160.0" />
			<path d="M160.0 89.7 A192 192 0 1 1 272.7 447.3" />
			<path d="M327.9 366.7 A132 132 0 0 1 138.4 315.9" />
			<path d="M125.0 239.9 A132 132 0 0 1 196.1 138.4" />
			<path d="M272.1 125.0 A132 132 0 0 1 377.5 307.6" />
			<path d="M211.7 199.3 A72 72 0 1 1 184.7 246.0" />
		</g>
		<path
			d="M141.4 141.4 A162 162 0 0 1 380.1 360.1 L334.1 321.6 A102 102 0 1 0 167.7 205.0 L256.0 256.0"
			fill="none"
			:stroke="`url(#${gradientId})`"
			stroke-width="26"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</svg>
</template>
